#!/usr/bin/env python3
"""Train the baseline model (IMPLEMENTATION.md p.7 step 3).

One independent LightGBM (gradient boosting) classifier per tag-tree
"group" (category), trained on masked examples generated by
``common.masking`` (suffix-masking scheme, see that module's docstring).
Evaluated on a held-out split done *by lemma* (``common.splits``) so no
form of the same lexeme leaks between train and val/test
(IMPLEMENTATION.md p.7 step 5).

Usage
-----
    /home/alex/.venv/bin/python3 train_baseline.py \\
        --forms forms.tsv --tag-tree tag_tree.json \\
        --out artifacts/baseline [--limit-train N] [--max-positions-per-tag K]

Run with a small ``--limit-train``/``--limit-eval`` for a quick smoke test;
omit them (or pass 0) to train on the full dataset.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common.baseline_model import BaselineModel
from common.dataset import iter_split
from common.masking import MaskedExample, sample_masked_examples
from common.tag_tree import TagTree


def collect_examples(
    forms_path: str,
    split: str,
    tree: TagTree,
    rng: random.Random,
    limit_rows: int,
    max_positions_per_tag: int,
) -> List[MaskedExample]:
    examples: List[MaskedExample] = []
    n_rows = 0
    for row in iter_split(forms_path, split, limit=limit_rows or None):
        n_rows += 1
        examples.extend(
            sample_masked_examples(
                row.word, row.lemma, row.tag, tree, rng, max_positions_per_tag
            )
        )
    print(f"[{split}] rows={n_rows} masked_examples={len(examples)}", file=sys.stderr)
    return examples


def evaluate(model: BaselineModel, examples: List[MaskedExample]) -> Dict[str, dict]:
    per_group_correct: Dict[str, int] = defaultdict(int)
    per_group_total: Dict[str, int] = defaultdict(int)
    for ex in examples:
        pred = model.predict_letter(
            ex.group, ex.word, ex.lemma, ex.known_prefix, ex.allowed_letters
        )
        per_group_total[ex.group] += 1
        if pred == ex.target_letter:
            per_group_correct[ex.group] += 1

    report: Dict[str, dict] = {}
    total_correct = total_count = 0
    for group in sorted(per_group_total):
        correct, total = per_group_correct[group], per_group_total[group]
        report[group] = {
            "accuracy": correct / total,
            "n": total,
        }
        total_correct += correct
        total_count += total
    report["__overall__"] = {
        "accuracy": total_correct / total_count if total_count else 0.0,
        "n": total_count,
    }
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--forms", default="forms.tsv")
    parser.add_argument("--tag-tree", default="tag_tree.json")
    parser.add_argument("--out", default="artifacts/baseline")
    parser.add_argument(
        "--limit-train",
        type=int,
        default=0,
        help="cap on number of forms.tsv rows read for the train split (0 = all)",
    )
    parser.add_argument(
        "--limit-eval",
        type=int,
        default=0,
        help="cap on number of forms.tsv rows read for val/test (0 = all)",
    )
    parser.add_argument(
        "--max-positions-per-tag",
        type=int,
        default=3,
        help="max masked positions sampled per tag, to avoid over-weighting long tags",
    )
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    tree = TagTree.load(args.tag_tree)

    t0 = time.time()
    train_examples = collect_examples(
        args.forms, "train", tree, rng, args.limit_train, args.max_positions_per_tag
    )
    val_examples = collect_examples(
        args.forms, "val", tree, rng, args.limit_eval, args.max_positions_per_tag
    )
    test_examples = collect_examples(
        args.forms, "test", tree, rng, args.limit_eval, args.max_positions_per_tag
    )

    by_group: Dict[str, List[MaskedExample]] = defaultdict(list)
    for ex in train_examples:
        by_group[ex.group].append(ex)

    model = BaselineModel(tree)
    fit_report: Dict[str, dict] = {}
    for group, examples in by_group.items():
        fit_report[group] = model.fit_group(group, examples)
        print(
            f"  fit group={group!r} n={len(examples)} -> {fit_report[group]}",
            file=sys.stderr,
        )

    val_report = evaluate(model, val_examples) if val_examples else {}
    test_report = evaluate(model, test_examples) if test_examples else {}

    out_dir = Path(args.out)
    model.save(out_dir)
    metrics_path = out_dir.parent / "baseline_metrics.json"
    metrics_path.parent.mkdir(parents=True, exist_ok=True)
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "fit": fit_report,
                "val": val_report,
                "test": test_report,
                "elapsed_seconds": time.time() - t0,
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    print(f"saved model -> {out_dir}")
    print(f"saved metrics -> {metrics_path}")
    if val_report:
        print(f"val overall accuracy: {val_report['__overall__']['accuracy']:.4f}")
    if test_report:
        print(f"test overall accuracy: {test_report['__overall__']['accuracy']:.4f}")


if __name__ == "__main__":
    main()
