/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.alex73.grammardb.check;

/**
 *
 * @author alex
 */
public class DbUtilPanel extends javax.swing.JPanel {

    /**
     * Creates new form DbUtilPanel
     */
    public DbUtilPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheck = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnMakeCache = new javax.swing.JButton();

        btnCheck.setText("Праверка");
        add(btnCheck);

        btnSort.setText("Сартаванне");
        add(btnSort);

        btnMakeCache.setText("Стварэнне кэшу");
        add(btnMakeCache);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCheck;
    public javax.swing.JButton btnMakeCache;
    public javax.swing.JButton btnSort;
    // End of variables declaration//GEN-END:variables
}
