<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- Для LanguageTool патрэбны асобны модуль, які потым пакуецца ў 
	maven артыфакт io.github.belarus:linguistics.grammardb.spell.languagetool:version -->

	<parent>
		<groupId>io.github.belarus</groupId>
		<artifactId>linguistics.grammardb</artifactId>
		<version>1.0.1</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>linguistics.grammardb.spell.languagetool</artifactId>
	<version>1.0.4</version>
	<packaging>pom</packaging>
	<name>GrammarDB-LanguageTool</name>
	<description>GrammarDB dictionary for LanguageTool</description>

	<build>
		<plugins>
			<plugin>
				<groupId>io.github.belarus</groupId>
				<artifactId>linguistics.grammardb.compiler</artifactId>
				<version>1.0.6</version>
				<executions>
					<execution>
						<id>text2dict</id>
						<goals>
							<goal>compile-lt-spell-checker</goal>
						</goals>
						<configuration>
							<inputText>${project.basedir}/../data-assembly/target/export/spellchecker/slovy-2008.txt</inputText>
							<inputInfo>${project.basedir}/be_BY.info</inputInfo>
							<outputDict>${project.build.directory}/be_BY.dict</outputDict>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<appendAssemblyId>false</appendAssemblyId>
							<descriptors>
								<descriptor>spell-assembly.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
